### ISSUE TITLE
Array params in variation - only first element is used

### ISSUE THREAD

**Issue by davidhoelzel** [qossmic/twig-doc-bundle#31]
e.g.:

```yaml 
variation:
 default:
    faqSnippets:
     - name: bla
       type: blub
     - name: blub
       type: bla
``` 
@danielaKay  has details for this problem
